# version: '3.9'
services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  celery:
    image: celery:latest
    volumes:
      - .:/app
    depends_on:
      - backend
      - rabbitmq
      - redis
      - db
    command: celery -A config worker --loglevel=info


  redis:
    image: redis:latest
    ports:
      - 6378:6379

  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432


  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - backend
      - rabbitmq
      - celery
      - redis
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']

  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node


volumes:
  postgres_data:

networks:
  sharehub:
    external: false
