# version: '3.9'
services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  celery:
    image: celery:latest
    volumes:
      - .:/app
    depends_on:
      - backend
      - rabbitmq
      - redis
      - db
    command: celery -A config worker --loglevel=info


  redis:
    image: redis:latest
    ports:
      - 6378:6379

  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432


  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - backend
      - rabbitmq
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555

  prometheus:
    networks:  
      - sharehub
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - ~/sharehub-volume/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    labels:
      org.label-schema.group: "monitoring"


volumes:
  postgres_data:

networks:
  sharehub:
    driver: bridge
