version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Run Migrations
          command: |
            docker-compose exec web python manage.py migrate

      - run:
          name: Run Tests
          command: |
            docker-compose exec web python manage.py test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
