# Generated by Django 5.0.3 on 2024-06-13 11:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likepost",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="likepost",
            index=models.Index(
                fields=["user", "post"], name="posts_likep_user_id_c28a72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "date_posted"], name="posts_post_author__493dcc_idx"
            ),
        ),
    ]
